name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  shelf_static: ^1.1.1
  postgres: ^2.6.1
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  build_runner: ^2.4.6
  json_serializable: ^6.7.1